repos:
- repo: https://github.com/nip-was-here/pre-commit-license-header
  rev: 5c350ce061054058047d3b9666594ee32361de94
  hooks:
    - id: license-header
      name: License Header
      language: python
      files: ^(\/?[^\.]+\/)*[^\.\/]+\.[^\/]+$
      args: [
        "-e", "README.md",
        "-e", "doc/*",
        "-e", "doc/**/*",
        "--template", ".license-header",
        "--copyright-holder", "nip"
      ]
- repo: https://github.com/nip-was-here/pre-commit-adr-toc
  rev: 1.0.0
  hooks:
    - id: adr-toc
      name: ADR Table of Content
      language: unsupported_script
      entry: adr-toc.sh
      pass_filenames: false
      files: '^doc/adr/(?!README\.md$).*\.md$'
